import {
  pgTable,
  uuid,
  text,
  date,
  numeric,
  boolean,
  timestamp,
  index,
} from "drizzle-orm/pg-core";
import { clients } from "./clients";
import { recurringInvoices } from "./recurring-invoices";

export const invoiceStatuses = ["draft", "sent", "paid", "overdue", "cancelled"] as const;
export type InvoiceStatus = (typeof invoiceStatuses)[number];

export const invoices = pgTable(
  "invoices",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    invoiceNumber: text("invoice_number").notNull().unique(),
    clientId: uuid("client_id").references(() => clients.id, { onDelete: "set null" }),
    dateOfIssue: date("date_of_issue").notNull(),
    dateDue: date("date_due").notNull(),
    status: text("status", { enum: invoiceStatuses }).notNull().default("draft"),
    subtotal: numeric("subtotal", { precision: 12, scale: 2 }).notNull().default("0"),
    taxPercentage: numeric("tax_percentage", { precision: 5, scale: 2 }).notNull().default("0"),
    taxAmount: numeric("tax_amount", { precision: 12, scale: 2 }).notNull().default("0"),
    discountPercentage: numeric("discount_percentage", { precision: 5, scale: 2 }).notNull().default("0"),
    discountAmount: numeric("discount_amount", { precision: 12, scale: 2 }).notNull().default("0"),
    total: numeric("total", { precision: 12, scale: 2 }).notNull().default("0"),
    currency: text("currency").notNull().default("LKR"),
    notes: text("notes"),
    category: text("category").notNull().default("other"),
    recurringInvoiceId: uuid("recurring_invoice_id").references(() => recurringInvoices.id, {
      onDelete: "set null",
    }),
    isAutoGenerated: boolean("is_auto_generated").notNull().default(false),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    index("invoices_client_idx").on(t.clientId),
    index("invoices_status_idx").on(t.status),
    index("invoices_created_idx").on(t.createdAt),
  ],
);
