"use server";

import { db } from "@/server/db/client";
import {
  recurringInvoices,
  recurringInvoiceItems,
  invoices,
} from "@/server/db/schema";
import { eq } from "drizzle-orm";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { computeNextGenerationDate } from "@/lib/types";

const RecurringItemInput = z.object({
  description: z.string().min(1),
  quantity: z.number(),
  unitPrice: z.number(),
  sortOrder: z.number().int().nonnegative(),
});

const RecurringTemplateInput = z.object({
  clientId: z.string().uuid(),
  currency: z.string().min(1),
  taxPercentage: z.number(),
  discountPercentage: z.number(),
  discountAmount: z.number(),
  notes: z.string().nullable().optional(),
  category: z.string().min(1),
  dayOfMonth: z.number().int().min(1).max(28),
  autoSendWhatsapp: z.boolean(),
});

export type RecurringTemplateInputData = z.infer<typeof RecurringTemplateInput>;
export type RecurringItemInputData = z.infer<typeof RecurringItemInput>;

export async function createRecurringTemplate(args: {
  template: RecurringTemplateInputData;
  items: RecurringItemInputData[];
  linkToInvoiceId?: string;
}) {
  const template = RecurringTemplateInput.parse(args.template);
  const items = z.array(RecurringItemInput).parse(args.items);

  return db.transaction(async (tx) => {
    const [row] = await tx
      .insert(recurringInvoices)
      .values({
        clientId: template.clientId,
        currency: template.currency,
        taxPercentage: String(template.taxPercentage),
        discountPercentage: String(template.discountPercentage),
        discountAmount: String(template.discountAmount),
        notes: template.notes ?? null,
        category: template.category,
        dayOfMonth: template.dayOfMonth,
        isActive: true,
        autoSendWhatsapp: template.autoSendWhatsapp,
        generatedCount: 1,
        nextGenerationDate: computeNextGenerationDate(template.dayOfMonth),
      })
      .returning();

    if (items.length > 0) {
      await tx.insert(recurringInvoiceItems).values(
        items.map((item, idx) => ({
          recurringInvoiceId: row.id,
          description: item.description,
          quantity: String(item.quantity),
          unitPrice: String(item.unitPrice),
          amount: String(Number(item.quantity) * Number(item.unitPrice)),
          sortOrder: item.sortOrder ?? idx,
        })),
      );
    }

    if (args.linkToInvoiceId) {
      await tx
        .update(invoices)
        .set({
          recurringInvoiceId: row.id,
          isAutoGenerated: false,
          updatedAt: new Date(),
        })
        .where(eq(invoices.id, args.linkToInvoiceId));
    }

    revalidatePath("/recurring");
    if (args.linkToInvoiceId) revalidatePath(`/invoices/${args.linkToInvoiceId}`);
    return row;
  });
}

export async function setRecurringActive(id: string, active: boolean) {
  await db
    .update(recurringInvoices)
    .set({ isActive: active, updatedAt: new Date() })
    .where(eq(recurringInvoices.id, id));

  revalidatePath("/recurring");
}

export async function deleteRecurringTemplate(id: string) {
  await db.delete(recurringInvoices).where(eq(recurringInvoices.id, id));
  revalidatePath("/recurring");
}
